---
title: "Homework 2 AM212"
date: 2024-10-5
author:
  - name: Kevin Silberberg
    id: 1900136
    orcid: 0009-0009-4825-1865
    email: ksilberb@ucsc.edu
    affiliation:
      - name: University of California Santa Cruz
        city: Santa Cruz
        state: CA
        href: www.ucsc.edu
format:
  html:
    theme: cosmo
    toc: true
    code-links:
      - icon: github
        href: https://github.com/KevySilb/AM212
---

# Haberman Exercise 2.3.8

## Problem definition 
The heat equation with homogenous boundary conditions: 

\begin{equation}\tag{1}\label{eq:heat}
	\begin{cases}
		u_t = ku_{xx} - \alpha u \\
		u(0, t) = 0 \\
		u(L, t) = 0
	\end{cases}
\end{equation}

### Part a

What are the possible equilibrium temperature distributions if $\alpha > 0$?

An equilibrium temperature distribution is such that the time derivative of temperature is zero ($u_t = 0$). Let us solve the homogenous BVP:

\begin{equation}\tag{2}\label{eq:steady}
	ku_{xx} - \alpha u = 0, u(0) = 0, u(L) = 0
\end{equation}

Before proceeding it is important to note that $k$ corresponds to the $\textbf{thermal diffusivity}$ of the material and is made of $K_0$ the $\textbf{thermal conductivity}$, $c$ $\textbf{specific heat capacity}$, and $\rho$ $\textbf{mass density}$ such that

$$k = \frac{K_0}{c\rho}$$ where $k > 0$

Let $u(x) = e^{rx}$, the characteristic polynomial becomes:

$kr^2 - \alpha = 0$

where the roots are 

$r = \pm \sqrt{\frac{\alpha}{k}}$

the solution of positive real roots:

$$u(x) = c_1e^{\sqrt{\frac{\alpha}{k}}x} + c_2e^{-{\sqrt{\frac{\alpha}{k}}x}}$$

plugging in the boundary conditions:

\begin{align}
	&\bigg[\begin{matrix}
		1 & 1 \\
		e^{\sqrt{\frac{\alpha}{k}}L} & e^{-\sqrt{\frac{\alpha}{k}}L}
	\end{matrix}\bigg]
	\bigg[\begin{matrix}
		c_1 \\
		c_2
	\end{matrix}\bigg] = 
	\bigg[\begin{matrix}
		0 \\
		0
	\end{matrix}\bigg] \\
	&\det{\bigg(\bigg[\begin{matrix}
		1 & 1 \\
		e^{\sqrt{\frac{\alpha}{k}}L} & e^{-\sqrt{\frac{\alpha}{k}}L}
	\end{matrix}\bigg]\bigg)} = e^{-\sqrt{\frac{\alpha}{k}}L} - e^{\sqrt{\frac{\alpha}{k}}L} = -2\sinh{(\sqrt{\frac{\alpha}{k}}L)}
\end{align}

$c_1 = c_2 = 0$

This leaves us with only a trivial solution $u(x) = 0$.

Thus if $\alpha$ is strictly positive the only possible equilibrium temperature distribution is zero everywhere.

### Part b

Solve the time dependent problem with IC $u(x, 0) = f(x)$ if $\alpha > 0$ and analyze temperature as $t \rightarrow \infty$ and compare with part a.

The IBVP:

\begin{equation}\tag{3}\label{eq:ibvp}
	\begin{cases}
		u_t = ku_{xx} - \alpha u \\
		u(x, 0) = f(x) \\
		u(0, t) = 0 \\
		u(L, t) = 0
	\end{cases}
\end{equation}

#### Separation of variables

Let

\begin{align}
	u(x, t) &= X(x)T(t) \\
	u_t &= XT' \\
	u_{xx} &= X''T
\end{align}

Plugging into \ref{eq:ibvp}

\begin{align}
	XT' &= kX''T - \alpha XT \\
	\frac{T'}{kT} - \frac{\alpha}{k} &= \frac{X''}{X} = \lambda
\end{align}

The solution of the eigen-value problem $X''(x) = \lambda X(x),  X(0) = X(L) = 0$ is 

\begin{align}
	X_n(x) = \sin{(\frac{n\pi x}{L})}  && \lambda_n = -\big(\frac{n\pi}{L}\big)^2 && n = 1, 2, 3, ...
\end{align}

Solving for the IVP:

$$T' = \lambda_n kT + \alpha T$$

Let $T_n(t) = e^{rt}$

the characteristic polynomial:

$r - \lambda_n k - \alpha = 0$

with a single root:

$r = \lambda_n k + \alpha$ 

thus the solution to the BVP:

$$u(x, t) = \sum_{n=1}^{\infty} a_n\sin{(\frac{n\pi x}{L})}e^{(-k(\frac{n\pi}{L})^2 + \alpha)t}$$

Applying the initial condition:

\begin{align}
	u(x, 0) = \sum_{n=1}^{\infty} a_n\sin{(\frac{n\pi x}{L})} &= f(x) \\
	\int_0^L \sum_{n=1}^{\infty} a_n\sin{(\frac{n\pi x}{L})}\sin{(\frac{m\pi x}{L})}dx &= \int_0^Lf(x)\sin{(\frac{m\pi x}{L})}dx \\
	\sum_{n=1}^{\infty}\int_0^L a_n\sin{(\frac{n\pi x}{L})}\sin{(\frac{m\pi x}{L})}dx &= \int_0^Lf(x)\sin{(\frac{m\pi x}{L})}dx
\end{align}

all terms in the integral cancel when $n = m$ (Sturm-Louiville) due to the eigenfunctions forming an orthonormal basis.

Let us solve for the coefficient $a_n$ on the LHS:

\begin{align}
	a_n\int_0^L\sin^2{(\frac{n \pi x}{L})}dx \\
	\text{Let} \ \ u &= \frac{n \pi x}{L} \\
	\frac{du}{dx} &= \frac{n \pi}{L} \\
	dx &= \frac{L}{n \pi}du \\ 
\end{align}

\begin{align}
a_n\frac{L}{n\pi}\int_0^{n \pi}\sin^2{(u)}du &= a_n\frac{L}{n\pi}\bigg[\frac{1}{2}(x - \sin{(x)}\cos{(x)})\bigg\vert_0^{n \pi}\bigg] \\
&= a_n \frac{L}{2} \\
a_n &= \frac{2}{L} \int_0^L f(x) \sin{(\frac{n \pi x}{L})}dx
\end{align}

the full solution to the the IBVP of (\ref{eq:heat}) is thus, 

\begin{equation}\tag{4}\label{eq:sol}
	u(x, t) = \sum_{n=1}^{\infty} a_n\sin{(\frac{n\pi x}{L})}e^{(-k(\frac{n\pi}{L})^2 + \alpha)t}
\end{equation}

If we take the limit as ($t \rightarrow \infty$)

\begin{align}
	\lim_{t \rightarrow \infty} \bigg[ e^{\alpha t}\sum_{n=1}^{\infty} e^{-k(\frac{n \pi}{L})^2 t}\bigg]
\end{align}

Since $k, L, \alpha$ are all positive real numbers we can clearly see that the limit goes to zero since the infinite sum appraoches $e^{-\infty}$ much faster than $e^{\alpha t}$ approaches $e^{\infty}$
